### ISSUE TITLE
Allow for installing the template in the content folder (?)

### ISSUE THREAD

**Issue by olayway** [flowershow/flowershow#269]
Not sure if we want to support it but:

It's not possible atm to install the template inside the content folder. This will result in the following esbuild error, even though we have `.flowershow` specified in contentlayer config's `contentDirExclude`. 

```sh
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
Error: Found 1 problems in 1 documents.

 └── Encountered unexpected errors while processing of 1 documents. This is possibly a bug in Contentlayer. Please open an issue.
     
     • "index.md": UnexpectedMDXError: Error: Build failed with 1 error:
     _mdx_bundler_entry_point-8f9ad85f-55d1-40f7-81d2-a6e3869c4584.mdx:0:0: error: [plugin: @mdx-js/esbuild] Error: ELOOP: too many symbolic links encountered, stat '/home/ola/Projects/lifeitself/my-site/content/.flowershow/content/.flowershow/content/.flowershow/content/.flowershow/content/.flowershow/content/.flowershow/content/.flowershow/content/.flowershow/content/.flowershow/content/.flowershow/content/.flowershow/content/.flowershow/content/.flowershow/content/.flowershow/content/.flowershow/content/.flowershow/content/.flowershow/content/.flowershow/content/.flowershow/content/.flowershow/content/.flowershow/content/.flowershow/content/.flowershow/content/.flowershow/content/.flowershow/content/.flowershow/content/.flowershow/content/.flowershow/content/.flowershow/content/.flowershow/content/.flowershow/content/.flowershow/content/.flowershow/content/.flowershow/content/.flowershow/content/.flowershow/content/.flowershow/content/.flowershow/content/.flowershow/content/.flowershow/content/.flowershow/content'
         at Object.statSync (node:fs:1583:3)
         at walkDir (/home/ola/Projects/lifeitself/my-site/content/.flowershow/node_modules/remark-wiki-link-plus/dist/index.cjs.js:404:13)
         at /home/ola/Projects/lifeitself/my-site/content/.flowershow/node_modules/remark-wiki-link-plus/dist/index.cjs.js:385:16
         at Array.map (<anonymous>)
         at /home/ola/Projects/lifeitself/my-site/content/.flowershow/node_modules/remark-wiki-link-plus/dist/index.cjs.js:399:18
         at /home/ola/Projects/lifeitself/my-site/content/.flowershow/node_modules/remark-wiki-link-plus/dist/index.cjs.js:386:14
         at Array.reduce (<anonymous>)
         at /home/ola/Projects/lifeitself/my-site/content/.flowershow/node_modules/remark-wiki-link-plus/dist/index.cjs.js:385:16

```

**Comment by rufuspollock** [comment]
WONTFIX / DUPLICATE. Whilst i think it is reasonable to do this i think this relates to a bigger discussion about UX and behavior of self-publishing experience. I've moved the content of this to related discussion https://github.com/flowershow/flowershow/discussions/323
