### ISSUE TITLE
[Bug] Failed to clone Flowershow template in windows 11

### ISSUE THREAD

**Issue by Tony-zf1** [flowershow/flowershow#298]
I use windows power shell with admin to configure but failed, as the screenshot shows below.
<img width="734" alt="image" src="https://user-images.githubusercontent.com/79450935/202843121-acf0292e-517b-445b-b56b-22be590d3d6d.png">

**Comment by lapo-luchini** [comment]
Same of FreeBSD 13.1:

```sh
% npx flowershow@0.1.4 install
? Create Flowershow project in current directory? Yes
? Path to the folder with your markdown files docs
? Select a folder with your assets (attachments) assets
⠋  Creating Flowershow template in /usr/home/user/.flowershow
 ERROR  Failed to clone Flowershow template into /usr/home/user/.flowershow. This may be a problem with Flowershow. Please let us know about it by submitting an issue: https://github.com/flowershow/flowershow/issues.
DegitError: could not find commit hash for HEAD
    at Degit._cloneWithTar (/usr/home/user/.npm/_npx/e8b63b56405f0d67/node_modules/degit/dist/index-688c5d50.js:14258:10)
    at async Degit.clone (/usr/home/user/.npm/_npx/e8b63b56405f0d67/node_modules/degit/dist/index-688c5d50.js:14096:4)
    at async Installer.install (file:///usr/home/user/.npm/_npx/e8b63b56405f0d67/node_modules/flowershow/src/lib/Installer.js:131:13)
    at async install (file:///usr/home/user/.npm/_npx/e8b63b56405f0d67/node_modules/flowershow/src/lib/install.js:27:5) {
  code: 'MISSING_REF',
  ref: 'HEAD'
}
```

**Comment by olayway** [comment]
@lapo-luchini thank you for reporting this. Yes, you're right. Git is required to run our CLI, because degit needs it. I've just moved your comment to a separate issue. I think it's worth considering other options as we would like to make using Flowershow as seamless as possible also for non-technical users.
