### ISSUE TITLE
Broken links to random pages

### ISSUE THREAD

**Issue by olayway** [flowershow/flowershow#53]
## What happens
Sometimes internal links cause remark-wiki-link-plus errors (`TypeError: Cannot read properties of undefined (reading 'startsWith')`). I'm not sure how the pages that cause errors differ from the ones that don't though.

## Steps to reproduce
1. Create an internal link to `docs/advanced/contentlayer`, e.g. in `docs/essentials/layoutes` where I intended to add it.
2. This results in the following error:

```bash
File updated: docs/essentials/layouts.md
event - compiled successfully in 143 ms (184 modules)
 > ../../templates/default/content/_mdx_bundler_entry_point-fa98af60-6507-4bb3-90cd-a464f130e0cd.mdx:0:0: error: [plugin: @mdx-js/esbuild] TypeError: Cannot read properties of undefined (reading 'startsWith')
    at _objectSpread.pageResolver (/home/ola/Projects/lifeitself/flowershow/templates/default/node_modules/remark-wiki-link-plus/dist/index.cjs.js:208:17)
    at Object.exitWikiLink (/home/ola/Projects/lifeitself/flowershow/templates/default/node_modules/remark-wiki-link-plus/dist/index.cjs.js:73:26)
    at compile (file:///home/ola/Projects/lifeitself/flowershow/templates/default/node_modules/mdast-util-from-markdown/lib/index.js:302:40)
    at fromMarkdown (file:///home/ola/Projects/lifeitself/flowershow/templates/default/node_modules/mdast-util-from-markdown/lib/index.js:120:29)
    at parser (file:///home/ola/Projects/lifeitself/flowershow/templates/default/node_modules/@mdx-js/esbuild/node_modules/remark-parse/lib/index.js:15:12)
    at Function.parse (file:///home/ola/Projects/lifeitself/flowershow/templates/default/node_modules/unified/lib/index.js:273:12)
    at executor (file:///home/ola/Projects/lifeitself/flowershow/templates/default/node_modules/unified/lib/index.js:393:31)
    at new Promise (<anonymous>)
    at Function.process (file:///home/ola/Projects/lifeitself/flowershow/templates/default/node_modules/unified/lib/index.js:380:14)
    at process (file:///home/ola/Projects/lifeitself/flowershow/templates/default/node_modules/@mdx-js/esbuild/node_modules/@mdx-js/mdx/lib/util/create-format-aware-processors.js:46:22)
    0 │ # Layouts
      ╵ ^

Error: Found 1 problems in 1 documents.

 └── Encountered unexpected errors while processing of 1 documents. This is possibly a bug in Contentlayer. Please open an issue.
     
     • "docs/essentials/layouts.md": UnexpectedMDXError: Error: Build failed with 1 error:
     ../../templates/default/content/_mdx_bundler_entry_point-fa98af60-6507-4bb3-90cd-a464f130e0cd.mdx:0:0: error: [plugin: @mdx-js/esbuild] TypeError: Cannot read properties of undefined (reading 'startsWith')
         at _objectSpread.pageResolver (/home/ola/Projects/lifeitself/flowershow/templates/default/node_modules/remark-wiki-link-plus/dist/index.cjs.js:208:17)
         at Object.exitWikiLink (/home/ola/Projects/lifeitself/flowershow/templates/default/node_modules/remark-wiki-link-plus/dist/index.cjs.js:73:26)
         at compile (file:///home/ola/Projects/lifeitself/flowershow/templates/default/node_modules/mdast-util-from-markdown/lib/index.js:302:40)
         at fromMarkdown (file:///home/ola/Projects/lifeitself/flowershow/templates/default/node_modules/mdast-util-from-markdown/lib/index.js:120:29)
         at parser (file:///home/ola/Projects/lifeitself/flowershow/templates/default/node_modules/@mdx-js/esbuild/node_modules/remark-parse/lib/index.js:15:12)
         at Function.parse (file:///home/ola/Projects/lifeitself/flowershow/templates/default/node_modules/unified/lib/index.js:273:12)
         at executor (file:///home/ola/Projects/lifeitself/flowershow/templates/default/node_modules/unified/lib/index.js:393:31)
         at new Promise (<anonymous>)
         at Function.process (file:///home/ola/Projects/lifeitself/flowershow/templates/default/node_modules/unified/lib/index.js:380:14)
         at process (file:///home/ola/Projects/lifeitself/flowershow/templates/default/node_modules/@mdx-js/esbuild/node_modules/@mdx-js/mdx/lib/util/create-format-aware-processors.js:46:22)
     

SourceFetchDataError: {
  "_tag": "HandledFetchDataError"
}

```

## Notes **✅ 2022-08-04 Bugfix**

On investigation, the bug was related to filenames that were similar to the markdownFolder name, which in this case is 'content'. With further testing it was confirmed that this was the issue from remark-wiki-link-plus code that had a includes check`.includes(markdown folder name)`. The code has been updated in remark-wiki-link-plus repo to resolve this issue.

**Comment by khalilcodes** [comment]
@olayway updated to latest package v1.0.1 with implemented fix.

**Comment by olayway** [comment]
@khalilcodes Works! Thank you!
