### ISSUE TITLE
YAML properties with hyphens cause Build error

### ISSUE THREAD

**Issue by joesmusings** [flowershow/flowershow#636]
Discussed in https://github.com/datopian/flowershow/discussions/632

## Issue
YAML properties that contain a hyphen cause a build error

Example properties:

```
dg-publish: true
dg-publish: true
kanban-plugin: basic
```

## Example Error

```
SyntaxError: Arg string terminates parameters early
    at new Function (<anonymous>)
    at file:///vercel/path0/node_modules/next-mdx-remote/dist/index.js:64:35
    at Object.Kc [as useMemo] (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:60:240)
    at exports.useMemo (/vercel/path0/node_modules/react/cjs/react.production.min.js:25:208)
    at MDXRemote (file:///vercel/path0/node_modules/next-mdx-remote/dist/index.js:52:21)
    at Wc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
    at Zc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
    at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at $c (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
    at Zc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:145)
Error occurred prerendering page "/Home". Read more: https://nextjs.org/docs/messages/prerender-error
SyntaxError: Arg string terminates parameters early
    at new Function (<anonymous>)
    at file:///vercel/path0/node_modules/next-mdx-remote/dist/index.js:64:35
    at Object.Kc [as useMemo] (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:60:240)
    at exports.useMemo (/vercel/path0/node_modules/react/cjs/react.production.min.js:25:208)
    at MDXRemote (file:///vercel/path0/node_modules/next-mdx-remote/dist/index.js:52:21)
    at Wc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
    at Zc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
    at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at $c (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
    at Zc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:145)
info  - Generating static pages (4/6)
info  - Generating static pages (6/6)
> Export encountered errors on following paths:
	/[[...slug]]: /Home
Error: Command "npm run export" exited with 1
```

**Comment by AsmodaiP** [comment]
same

**Comment by rufuspollock** [comment]
@mohamedsalem401 can we check if this is something in remark-frontmatter or graymatter.

**Comment by olayway** [comment]
This was related to Flowershow Self-Hosted. WONTFIX
(It does happen in Cloud too, but can be fixed with wrapping the key in quotes, e.g. `"dg-publish": true` (it's a good practice anyway))
